name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        path: ./action-a
    - run: pwd 
    - run: ls -la ..
    - run: ls -la 
    - run: ls -la action-a 
    - uses: ./action-a
      env:
        MY_NAME: "Alain"
    - run: docker images
